---
openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  "/repositories":
    get:
      summary: List Repositories
      operationId: list_repositories_repositories_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
    post:
      summary: Add Repositories
      operationId: add_repositories_repositories_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/RepoRequest"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
    delete:
      summary: Remove Repositories
      operationId: remove_repositories_repositories_delete
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/RepoRequest"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/cleanup":
    post:
      summary: Cleanup Repositories
      operationId: cleanup_repositories_cleanup_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/RepoRequest"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    RepoRequest:
      properties:
        urls:
          items:
            type: string
          type: array
          title: Urls
      type: object
      required:
      - urls
      title: RepoRequest
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
